services:
  anvil-mainnet:
    build:
      context: ./images
      dockerfile: Dockerfile.anvil
    environment:
      - URL=${MAINNET_FORK_URL:-https://eth-mainnet.public.blastapi.io}
    ports:
      - "8545:8545"
    networks:
      - anvil-network

  anvil-polygon:
    build:
      context: ./images
      dockerfile: Dockerfile.anvil
    environment:
      - URL=${POLYGON_FORK_URL:-https://polygon-zkevm-mainnet.public.blastapi.io}
    ports:
      - "8546:8545"
    networks:
      - anvil-network

networks:
  anvil-network:
    driver: bridge 